{{- if or .Values.webhook.podMutatingWebhook.enabled .Values.webhook.pvcMutatingWebhook.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "topolvm.fullname" . }}-hook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ template "topolvm.fullname" . }}-mutatingwebhook
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "topolvm.fullname" . }}-hook
webhooks:
  {{- if .Values.webhook.pvcMutatingWebhook.enabled }}
  - name: pvc-hook.topolvm.cybozu.com
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    namespaceSelector:
      matchExpressions:
        - key: topolvm.cybozu.com/webhook
          operator: NotIn
          values: ["ignore"]
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      {{- with .Values.webhook.caBundle }}
      caBundle: {{ . }}
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "topolvm.fullname" . }}-controller
        path: /pvc/mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["persistentvolumeclaims"]
    sideEffects: None
  {{- end }}
  {{- if .Values.webhook.podMutatingWebhook.enabled }}
  - name: pod-hook.topolvm.cybozu.com
    admissionReviewVersions:
      - "v1"
      - "v1beta1"
    namespaceSelector:
      matchExpressions:
        - key: topolvm.cybozu.com/webhook
          operator: NotIn
          values: ["ignore"]
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      {{- with .Values.webhook.caBundle }}
      caBundle: {{ . }}
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "topolvm.fullname" . }}-controller
        path: /pod/mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
  {{- end }}
---
{{- end }}
