:global:
  componentName: topolvm
  feature_componentCompile: false

docs/antora.yml:
  name: topolvm
  title: TopoLVM

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
