apiVersion: v1
kind: Service
metadata:
  name: {{ template "topolvm.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: topolvm-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9443
