= Parameters

The parent key for all of the following parameters is `topolvm`.

== `namespace`

[horizontal]
type:: string
default:: `syn-topolvm`

The namespace in which to deploy this component.

== `images`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
topolvm:
  registry: quay.io
  repository: topolvm/topolvm-with-sidecar
  tag: 0.9.0
csi_provisioner:
  registry: k8s.gcr.io
  repository: sig-storage/csi-provisioner
  tag: v2.2.1
----

The `csi_provisioner` uses a separate image, bc the current implementation in `topolvm-with-sidecar:0.9.0` contains a bug.

This configuration shouldn't be touched and will be updated with future releases of this component.

== `deviceclasses`

[horizontal]
type:: list
default::
+
[source,yaml]
----
ssd:
  volume-group: vgssd
  spare-gb: 10
  default: true
----

Each key represents a different device class.

=== `volume-group`

[horizontal]
type:: string

Name of the LVM volumegroup to be used by this device class.

=== `spare-gb`

[horizontal]
type:: integer

This amount of space will be reserved on the volumegroup and not allocated or reported as free by TopoLVM.

=== `default`

[horizontal]
type:: string

If the storage class has no special parameter set, this device class will be used. However, one device class must be set as default.

=== Example

[source,yaml]
----
parameters:
  topolvm:
    deviceclasses:
      ssd:
        volume-group: vgssd
        spare-gb: 1
        default: true
      hdd:
        volume-group: vghdd
        spare-gb: 5
        default: false
----

== `storageclasses`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
ssd-local:
  class: ssd
  fstype: ext4
  volumeexpansion: true
----

Each key represents a different storage class.

=== `class`

[horizontal]
type:: string

Key of the device class used by this storage class.

=== `fstype`

[horizontal]
type:: string

The filesystem that's used with this storage class.

=== `volumeexpansion`

[horizontal]
type:: boolean

Should volume expansion be allowed with this storage class.

=== `retainpolicy`

[horizontal]
type:: string

Optional, can be used to overwrite the default retain policy.

=== Example

[source,yaml]
----
parameters:
  topolvm:
    storageclasses:
      ssd-local:
        class: ssd
        fstype: ext4
        volumeexpansion: true
        retainpolicy: Retain
      hdd-local:
        class: hdd
        fstype: ext4
        volumeexpansion: true
----

== `helmValues`

[horizontal]
type:: dict
default:: See `class/defaults.yaml`

Values passed to Helm. See https://github.com/topolvm/topolvm/blob/main/charts/topolvm/values.yaml

== Example

[source,yaml]
----
parameters:
  topolvm:
    deviceclasses:
      ssd:
        volume-group: vgssd
        spare-gb: 10
        default: true

    storageclasses:
      ssd-local:
        class: ssd
        fstype: ext4
        volumeexpansion: true
----
