apiVersion: v2
type: application

home: https://github.com/topolvm/topolvm
name: topolvm
description: Topolvm
version: 2.0.1
appVersion: 0.8.3
kubeVersion: ">=1.18.0"
sources:
  - https://github.com/topolvm/topolvm

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.5.3
    condition: cert-manager.enabled
